name: .NET Continuous Deployment

on:
  push:
    branches: [ master ]
    paths: 
      - src/DiscosWebSdk/DiscosWebSdk/**
  workflow_dispatch:
jobs:

  test:
    name: Test Project (Real API)
    runs-on: ubuntu-latest
    env:
      DISCOS_API_KEY: ${{ secrets.DISCOS_API_KEY }}
      DISCOS_API_URL: https://discosweb.esoc.esa.int/api/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Test against real API
      run: dotnet test --logger GitHubActions ./src/DiscosWebSdk/DiscosWebSdk.sln

  semantic-release:
    needs: test
    name: Create a Package Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Need the full commit history for conventional commit
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: Create Nuget Package
      run: dotnet build -c Release ./src/DiscosWebSdk/DiscosWebSdk/DiscosWebSdk.csproj && dotnet pack -c Release -p:PackageVersion=${{ steps.tag_version.outputs.new_version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o . ./src/DiscosWebSdk/DiscosWebSdk/DiscosWebSdk.csproj
    - name: Upload Package for Publishing
      uses: actions/upload-artifact@v4
      with:
        name: PackedLib
        path: ./*.nupkg
    - name: Upload Symbols for Publishing
      uses: actions/upload-artifact@v4
      with:
        name: PackedSymbols
        path: ./*.snupkg
  
  github-publish:
    needs: semantic-release
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
    - name: Download built project  
      uses: actions/download-artifact@v4
      with:
        name: PackedLib
    - name: Download packed Symbols
      uses: actions/download-artifact@v4
      with:
        name: PackedSymbols
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Push Package to GitHub
      run: dotnet nuget push --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/hughesjs/index.json" *.nupkg

  nuget-publish:
    needs: semantic-release
    name: Publish to Nuget
    runs-on: ubuntu-latest
    steps:
    - name: Download built project  
      uses: actions/download-artifact@v4
      with:
        name: PackedLib
    - name: Download packed Symbols
      uses: actions/download-artifact@v4
      with:
        name: PackedSymbols
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Push Package to Nuget
      run: dotnet nuget push --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" *.nupkg
